name: GH Login With Token
author: David G. Moore, Jr., <david@dgmjr.io>
description: Logs the user in with the provided GITHUB_TOKEN

branding:
  icon: log-in
  color: green

inputs:
  git-token:
    required: true
    description: GitHub Token

runs:
  using: composite
  steps:
    - id: gh-auth-login-with-token
      name: GH Login With Token
      run: echo "${{ inputs.git-token }}" | gh auth login --with-token
      shell: pwsh
    - id: gh-auth-setup-git
      name: GH Auth Setup Git
      run: gh auth setup-git
      shell: pwsh
